### ISSUE TITLE
p:timeline - drag&drop event between groups doesn't keep the date range

### ISSUE THREAD

**Issue by spauny** [primefaces-extensions/primefaces-extensions.github.com#332]
Hello,

Using the timeline component, if you drag and drop an event from one group to the other, the event visually doesn't keep the date range. If you inspect the actual start date and end date, they are correct. Even if I try to reload/update the model, the even doesn't change. Only if I refresh the page / recreate the model completely, the event appears to have the correct date range. 

Also after you drag and drop the event from one group to another, you cannot increase it anymore (increase the date range). The tiny bar doesn't appear on any edge anymore. 

You can view both behaviours on the online showcase: http://www.primefaces.org/showcase-ext/sections/timeline/grouping.jsf

**Comment by ova2** [comment]
Have you tried to set snapEvents="true"? If it doesn't work, can you ask in the native Timeline forum please? I have no clue why it behaves in this manner. Here some links to the native Timeline:

Docu: http://almende.github.io/chap-links-library/js/timeline/doc/
Example with groups (here it works as expected, probably an old version because I've updated Timeline recently): http://almende.github.io/chap-links-library/js/timeline/examples/example13_grouping.html

If it is a bug in the native Timeline, please report it here: https://github.com/almende/chap-links-library/issues Thanks.

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
