### ISSUE TITLE
p:timeline - the start and end options don't work when using groups

### ISSUE THREAD

**Issue by spauny** [primefaces-extensions/primefaces-extensions.github.com#333]
Hello,

When I use groups, the start and end dates of the timeline are always the beginning of the first event and the end of the last event, even if I try to set it to only 2 weeks. It works fine without groups...

http://www.primefaces.org/showcase-ext/sections/timeline/grouping.jsf

Thanks

**Comment by ova2** [comment]
Setting start / end is broken since 3.1.0. See https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/323 I'm not sure if it's a problem. Have you tried to ask in the forum of the nativ Timeline? Here is also the issue tracker of the native Timeline https://github.com/almende/chap-links-library/issues

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
