### ISSUE TITLE
customContentLayout with forms

### ISSUE THREAD

**Issue by raelianer** [primefaces-extensions/primefaces-extensions.github.com#342]
In the showcase it is stated that you can place any elements between layout panes:

http://www.primefaces.org/showcase-ext/sections/layout/customContentLayout.jsf

            <div style="padding:10px; margin-bottom:6px; border:1px solid red;"  
                 class="ui-widget-content ui-corner-all">  
                 This is a custom content between layout panes.  
                 <br/><br/>  
                 Any elements can be placed here.  
            </div>

But the full page layouts seem to depend on a surrounding form. As it is not allowed to nest forms, is it correct to asume that I cannot include forms? Or is there a way to use forms in different panes, so that I could include a [toolbar] (http://www.primefaces.org/showcase/ui/panel/toolbar.xhtml) in north pane next to a form in the center pane for example?

**Comment by ova2** [comment]
Sure, you can not nest forms in HTML. It's invalid. AFAIK, full page layout doesn't require surrounding form. It is required if you have attached p:ajax (for "resize" event and similar). Only p:ajax requires a form. You can place separate h:form inside pe:layoutPane. But I would suggest to use one big form rather than separate ones.
