### ISSUE TITLE
pe:exporter - does not honor exportable="false" within p:columnGroup 

### ISSUE THREAD

**Issue by bernerus** [primefaces-extensions/primefaces-extensions.github.com#345]
When using pe:exporter on a table where headers are defined using:

    <p:columnGroup type="header">
                                <p:row>
                                    <p:column exportable="false"/>
                                    <p:column headerText="#{blah}"/>
                                    <p:column headerText="#{blaha}"/>
                                </p:row>  
    </p:columnGroup>

    <p:column exportable="false">
                                   <h:selectBooleanCheckbox value="#{blah.selected}" />
    </p:column>
    <p:column> Blahdata</p:column>
    <p:column> Blahadata</p:column>

The header column gets exported anyway but the data column does not, leading to misalignment between header and data in the exported document.

**Comment by sudheerj** [comment]
Fixed for 6.0.

**Comment by SantoshCCS** [comment]
it's not fixed till now

**Comment by melloware** [comment]
@SantoshCCS Are you saying it is or is NOT fixed?

**Comment by SantoshCCS** [comment]
is NOT fixed in primefaces extension 6.0.
The header column gets exported anyway but the data column does not, leading to misalignment between header and data in the exported document.

**Comment by melloware** [comment]
OK please create a reproducible test case using this PF sample starter project.

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem. You can just run it with "mvn clean jetty:run" and it will start and run on localhost:8080.

Once you have reproduced it please submit a NEW issue and you can just reference this old issue.
