### ISSUE TITLE
pe:fluidGridItem and dynamic ui:include don't work togheter

### ISSUE THREAD

**Issue by fcanevar** [primefaces-extensions/primefaces-extensions.github.com#349]
I'm trying to use the fluidGrid component in my application, but I'm having a problem right away.
The layout that I'm trying to "fluidify" has a dynamic ui:include, apparently the component is trying to determinate it statically.

Here is my original code:
```
<c:forEach items="#{bean.items}" var="item" >
 	<ui:include src="/#{item.code}.xhtml">
 		<ui:param name="item" value="#{item}" />
 	</ui:include>
</c:forEach>
```
Here is my fluid code:
```
<pe:fluidGrid value="#{bean.fluidItems}" var="item" fitWidth="true">
    <pe:fluidGridItem>
 	<ui:include src="/#{item.code}.xhtml">
 		<ui:param name="item" value="#{item}" />
        </ui:include>
    </pe:fluidGridItem>
</pe:fluidGrid>
```
The error that I get is:
```
/.xhtml Not Found in ExternalContext as a Resource
```

Thanks

**Comment by ova2** [comment]
`/#{item.code}.xhtml` in ui:include can not be evaluated at render time because ui:include is a tag handler and gets evaluated at early JSF phase. This is because you get `/.xhtml` instead of `/#{item.code}.xhtml`. This is a pitfal of JSF beginners. Please read e.g. about the difference `c:forEach` (tag handler) and `ui:repeat` (component). The same is valid for all JSF / PrimeFaces components. Your code will not work with PrimeFaces data itereation components too.
