### ISSUE TITLE
Upgrade DocumentViewer's pdf.js

### ISSUE THREAD

**Issue by clintsmart** [primefaces-extensions/primefaces-extensions.github.com#374]
If there is a checked checkbox within the PDF, the checks are rendering as numbers and not checks.  I believe this is an issue with PDF.js, but was resolved here:

https://github.com/mozilla/pdf.js/pull/5251

**Comment by clintsmart** [comment]
Does this mean an update isn't expected to be available any time soon?

**Comment by tandraschko** [comment]
we currently don't have any active commiter which maintains the component. Same goes for CodeMirror.
We have 2 solutions
1) maintain it and be member of our team
2) we will remove it

**Comment by ova2** [comment]
CodeMirror stays, but will not be released anymore. This is a separate sub-project. In short words, CodeMirror will be "frozen" until somebody would like to maintain it.

Spotlight will be removed (we have the same functionality in PrimeFaces). Created a task for uns https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/387

DocumentViewer should be moved to the separate project too. We don't want to maintain it due to low interest. If somebody will move it, it's good, otherwise it will be removed.

**Comment by melloware** [comment]
After spending about 4 hours fighting this component over the weekend I have now come to  the conclusion it should be removed from PFE if no one wants to maintain it.  I give a lot of credit to the original developer for getting this working in the first place as it requires some really interesting tricks to try and get it working.  I was not able to successfully upgrade the component and some of the pain points include...

1. Having to convert images to BASE64 in the viewer.css every time.
2. PDF.JS is actually mutliple JS files which have hard coded URL's in them that have to be searched and replaced with Primefaces.getResource().
3. Something about how the locale's worked has changed.
4. Because the code does a client side eval(js) to evaluate the javascript getting the errors and line numbers of errors is really difficult to debug.

**Comment by tandraschko** [comment]
1) and 2) could be done via java, like in the CKEditor: https://github.com/primefaces-extensions/resources-ckeditor/blob/master/src/main/java/org/primefaces/extensions/ckeditor/ResourceModifier.java
There are several places where the JSF resources references must be used. Doing this everytime manually is not a option anymore :)

not sure about 3) and 4).

**Comment by melloware** [comment]
I have successfully updated to PDF.js 1.5.188 which is the latest stable release version up from version 1.0.21.  This was a pain in the butt but I took notes for the next time so it will be much easier.  I also modified the Renderer to handle Locale's using same utility used in Calculator and TimePicker so it is consistent.

**Comment by tandraschko** [comment]
Cool stuff!

**Comment by melloware** [comment]
@ova2 or @tandraschko can we delete the pdf.js fork our of our PF repo.  We don't do anything with this fork and it should be removed.  I can't imagine why we would fork it at this point in its maturity.

https://github.com/primefaces-extensions/pdf.js

**Comment by tandraschko** [comment]
done!

**Comment by melloware** [comment]
@JuanMiguelBG can you review the SNAPSHOT 6.1 version of the DocumentViewer to make sure it is working for you.  I know you submitted some patches last July around Firefox sizing for other languages and I can make those same changes again but I am concerned that anytime w upgrade DocumentViewer there is these customizations in the PDF.js javascript that could get lost.  

The particular types of commits I am concerned about is this one:  https://github.com/primefaces-extensions/core/pull/32/commits/9f81a61ecdf173cab32a6e352607632c4c31b7fd
