### ISSUE TITLE
MasterDetail - XSS Vulnerability not escaping Level body

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#408]
```
<pe:masterDetailLevel level="1">
    <f:facet name="label">
        <h:outputText value="&amp;"/>
    </f:facet>
    <h:outputText value="&amp;"/>
</pe:masterDetailLevel>
```

results in the following rendered output:

```
&amp;
&
```

Expected rendered output:

```
&
&
```

I'm using PFE 6.0.0

**Comment by tandraschko** [comment]
Please provide a PR, otherwise it will likely be closed as "won't fix" in the future.
PFE is a community based project, so every contribution is welcome.

**Comment by jepsar** [comment]
Let me see what I can do. Just as a reference:

https://github.com/primefaces-extensions/core/blob/1fad689c1337df12c9c8dca2ac12e77f7f2faa36/src/main/java/org/primefaces/extensions/component/masterdetail/MasterDetailRenderer.java#L253

**Comment by melloware** [comment]
@jepsar I just tested this myself and the bug is actually not quite what you think.  The facet header is doing the right thing by showing you &amp;.  Change your facet to the following:

```
   <f:facet name="label">
        <h:outputText value="&amp;" escape="false"/>
    </f:facet>
```
The issue is in the body of the master detail it should be encoding that one as &amp; as well but it is incorrectly rendering & which means it is somehow not respecting the escape=true flag which is the default on h:outputText.

So to repeat the facet header is doing the right thing just add escape="false".  Now figuring out why the body is ignoring that flag is the real bug.

**Comment by jepsar** [comment]
@melloware Thanks, I have already added `escape=false` the output in my facet to fix it there. In the showcase a label is used with a `outputFormat` with (default) escaping, that got me confused.

http://www.primefaces.org/showcase-ext/sections/masterDetail/complexNavigation.jsf

**Comment by melloware** [comment]
OK I fixed with this commit: https://github.com/primefaces-extensions/core/commit/9e751c179f5f249a23a989aceaa1907719a274b2

Here is the issue in a nutshell...
1. The facet is encoded using FastStringWriter.
2. ResponseWriter is normally used to write output which handles all the escaping.
3. The string encoded by FastStringWriter is used in the label so it is never escaped.
4. I use StrEscapeUtils.unescapeHtml4 to convert any HTML back just like ResponseWriter would.

**Comment by tandraschko** [comment]
we should really check if we need FastStringWriter - Probably it's already used inside the JSF impl. I know we have something in MyFaces.

**Comment by melloware** [comment]
I noticed there is a FastStringWriter both in PF and PFE Utils.  I was about to delete the one in PFE and use the one in PF utils.   Let me know if there is a better solution!

**Comment by tandraschko** [comment]
Personally i would analyze why it was used and directly write inside the ResponseWriter. MyFaces probably already used a FastStringWriter inside the ReponseWriter.

**Comment by melloware** [comment]
It seems to me the only times its used in both PF and PFE is when you don't want to write directly to the REsponse Writer and need to encode something and then use that value somewhere else.  Like this bug..

They need to encode the label facet and then assign it to the menu item .value().
```java
                    final UIComponent facet = mdl.getFacet(FACET_LABEL);
                    if (facet != null) {
                        // swap writers
                        ResponseWriter writer = fc.getResponseWriter();
                        FastStringWriter fsw = new FastStringWriter();
                        ResponseWriter clonedWriter = writer.cloneWithWriter(fsw);
                        fc.setResponseWriter(clonedWriter);

                        // render facet's children
                        facet.encodeAll(fc);

                        // restore the original writer
                        fc.setResponseWriter(writer);

                        // set menuitem label from facet
                        menuItem.setValue(StringEscapeUtils.unescapeHtml4(fsw.toString()));
                    }
````

**Comment by tandraschko** [comment]
Ah i see, than it's ok. But would be great if PFE would reuse the class from PF then.

**Comment by melloware** [comment]
I just deleted the PFE one.  And you are right it looks like JSF-IMPL has a FastStringWriter but that would tie it to the specific impl MyFaces or Mojarra which is why this FastStringWriter was probably created.  Thanks!
