### ISSUE TITLE
Showcase: Responsive Layout

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#444]
Would anyone like to migrate our showcase to the current layout of the PF showcase? https://www.primefaces.org/showcase ?

I think we can make the menu static on the left side.

**Comment by Rapster** [comment]
It's just my opinion, but I actually like the PE showcase, it's indeed less stylish than PF but it's quite simple to go through it :)

**Comment by melloware** [comment]
I too like the PE showcase because i also like the right hand panel that shows the different examples and Tag documentation right there.  I find that incredibly useful.    I totally understand why PF does it with a PDF link its a huge project with 10X the amount of components of PE.

That being said if you felt strongly about it that it needed to be done would you want us to use the showcase layout exactly?   We also don't have a PDF to link to for a documentation tab so we would have to figure out how to do the inline documentation.

**Comment by tandraschko** [comment]
I think we could make the left menu static and place our tag documentation inside the documentation tab, where PF links the PDF.

I think its not a big deal and it would be very simple, too. It's just a little bit effort, therefore i asked the team if anyone would like to do it :)
