### ISSUE TITLE
pe:documentViewer: Add missing pdf.js options (pagemode, nameddest)

### ISSUE THREAD

**Issue by Gigasgagasmann** [primefaces-extensions/primefaces-extensions.github.com#445]
*) "pagemode"
*) "nameddest"
https://github.com/mozilla/pdf.js/wiki/Viewer-options

**Comment by melloware** [comment]
Fixed with commit:  https://github.com/primefaces-extensions/core/commit/9f21ea797c4830a55213a94762a3303b9ec0f687

You can try it out i published the latest SNAPSHOT against PF6.1RC2 here: https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/6.1.0-SNAPSHOT/

**Comment by Gigasgagasmann** [comment]
Thanks, I will test it the in the next few days.

**Comment by Gigasgagasmann** [comment]
Thanks, works great.

**Comment by melloware** [comment]
awesome!  Thanks for testing.
