### ISSUE TITLE
Exporter - missing Support for exportFunction

### ISSUE THREAD

**Issue by Hamsterbau** [primefaces-extensions/primefaces-extensions.github.com#481]
In Primefaces it is possible to define a exportFunction per column on a datatable to export another cell value.

This exportFunction will be ignored from Primefaces Extensions Exporter (6.1.0).

Would be nice if this feature will also be implemented in the Extensions Exporter.

Thanks

Daniel

**Comment by melloware** [comment]
I will look at how PrimeFaces does it and see if I can do the same thing in our Exporter.

**Comment by melloware** [comment]
Fixed with this commit:  https://github.com/primefaces-extensions/core/commit/50f615af5752a6bce3c631397af4b060f4ad1e4b

**Comment by melloware** [comment]
I put a SNAPSHOT JAR out there if you want to test but use at your own risk.

https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/6.2-SNAPSHOT/

**Comment by Hamsterbau** [comment]
Wow that was quick! I can check it out on monday, thanks 🙂

**Comment by Rapster** [comment]
Not related to this topic but, since when we decided to move the version into something like 6.2 instead of 6.1.2?

**Comment by sudheerj** [comment]
@melloware Great,Thanks. Is that used for customized export column?

**Comment by melloware** [comment]
@Rapster Typically the way it worked before I got involved is PFE only did releases that lined up with a major PF release.  So 6.1 for 6.1.0 and the next release will be 6.2 for 6.2.0.     I made the 6.1.1 to go with PF 6.1 because I had fixed so many issues from all the upgrades that I didn't want people to wait until 6.2.0.   At least that seems to be how it has gone in the past PFE only releases fixes to go with the PF Community Edition.  I have thought though because of this issue https://github.com/primefaces/primefaces/issues/2395 begin fixed in Elite 6.1.5 and this affects PFE of making an Elite 6.1.5 release but I wasn't sure yet how I would do that since if I release to Maven Central everyone will think they can use it against Community PF 6.1 which they won't.

@sudheerj Yes this works just like in PF if you declare...
```xml
<p:column exportFunction="#{controller.customExporter}">
    <h:outputText value="Hello"/>
</p:column>
```

It will use the custom exporter function for that column instead of printing "Hello" for that column.

**Comment by Hamsterbau** [comment]
The maven way is not working because master-pom is not in the snapshot repository.
But i will take the JAR and put it into our local repository with changed pom.xml for testing.

**Comment by melloware** [comment]
ahh yes I need to put the master pom out there too but for now yes just copy the JAR into your local repo.

**Comment by Hamsterbau** [comment]
Works for me :+1:

**Comment by melloware** [comment]
Thanks for testing and reporting this issue!

**Comment by melloware** [comment]
I just cut an Extensions 6.1.5 Elite release including this fix if you need it.  Read here:  https://forum.primefaces.org/viewtopic.php?f=14&t=52458
