### ISSUE TITLE
DataExporter: Arabic character encoding issue

### ISSUE THREAD

**Issue by Erfaan07** [primefaces-extensions/primefaces-extensions.github.com#508]
Dears,

I am using p:dataExporter  to export the table data to a pdf, but the Arabic character are not being displayed. I tried using ecoding="CP1252", ecoding="Windows-1252", ecoding="UTF-8", but nothing seems to work. Please help/advice.

**Comment by melloware** [comment]
2 things

1) I believe your issue is because of Font and not encoding like already described in this ticket: https://github.com/primefaces/primefaces/issues/2363

2) you mentioned p:dataExporter which is the core PrimeFaces exporter this project is for PrimeFaces Extensions exporter so I assume I can close this ticket?

**Comment by melloware** [comment]
@Erfaan07 I would recommend adding your comment to that ticket so they know more and more people are requesting this feature: 

https://github.com/primefaces/primefaces/issues/146

https://github.com/primefaces/primefaces/issues/2363

**Comment by melloware** [comment]
PR submitted to fix #146 finally.
