### ISSUE TITLE
Layout: With Cookies enabled layout doesn't respect initClosed property

### ISSUE THREAD

**Issue by Kameecoding** [primefaces-extensions/primefaces-extensions.github.com#561]
## 1) Version
Primefaces 6.1
Primefaces-extensions 6.1.1

## 2.) Expected behavior
I have a simple layout with 4 panes, North, Center, East, south, both North and south is fixed.
Center and East is resizable, East has initClose="true" the layout is using cookie to save state.
After logging out and then logging back in the east pane should always be closed.

## 3.) Actual behavior
After logout and logging back in the east panel is open regardless of previous state.

## 4.) debugging I have tried

In the cookie initClosed is always set to false, tried to set to true and then open the page, but that had no effect.

## Sample Code
```
<pe:layout
	resizeTitle="resize"
        fullPage="true"
	stateCookie="true"
	widgetVar="layout">
	<c:if test="#{resizeComponent ne null}">
		<p:ajax event="resize" update=":#{p:component(resizeComponent)}" />
	</c:if>

	<pe:layoutPane
		position="north"
		closable="false"
		resizable="false"
		spacingOpen="0">
		    <!-- ui:insert header here -->
	</pe:layoutPane>
        <pe:layoutPane
		position="center"
		resizable="true"
		size="50%">
		        <!-- ui:insert dataTable here -->
	</pe:layoutPane>
	<pe:layoutPane
		position="east"
        	resizable="true"
		initClosed="true"
		size="50%">
	               <!-- ui:insert detail panel here -->
	</pe:layoutPane>
	<pe:layoutPane
		position="south"
		resizable="false"
		closable="false">
		<!-- ui:insert footer here -->
	</pe:layoutPane>
</pe:layout>
```

**Comment by melloware** [comment]
Do me a favor can you Clone this repository https://github.com/primefaces/primefaces-test.git and make a small reproducible test case.

The attach the zip here so I can just run "mvn clean jetty:run" to see the behavior.

**Comment by Kameecoding** [comment]
[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/1937078/primefaces-test.zip)

Here is the example, there is no login/logout so the way I tried it is to simply close the browser tab and open the page again on a new one.

if east is closed when closing, then it is closed when I open the page.
if east is open when closing, then it is open when I open the page, even though initClose is set to true

**Comment by melloware** [comment]
Awesome thanks for the sample!  I will see what I find out debugging.

**Comment by melloware** [comment]
OK when I first go to the page the cookie has these values:
```javascript
{"north":{"size":15,"initClosed":false,"initHidden":false},"south":{"size":15,"initClosed":false,"initHidden":false},"east":{"size":765,"initClosed":true,"initHidden":false}}
```

However when I open East panel and close the browser the cookie has these values.
```javascript
{"north":{"size":15,"initClosed":false,"initHidden":false},"south":{"size":15,"initClosed":false,"initHidden":false},"east":{"size":765,"initClosed":false,"initHidden":false}}
```
So I think once you choose storing the state in a cookie it has to remember the last "state" of the page.  So because east was open it says rememeber that east is open the next time you come to the page.  So I think this is actually expected behavior.  if you want your Layout to be reset every time someone comes to the page then you can't use the client side cookie to remember their settings.

**Comment by Kameecoding** [comment]
I disagree with this being the expected behavior. The state of the panel whether is open should be overridden by initClosed property, or the property has confusing naming.

For example for us it causes the issue that we have a dataTable in the Center panel and parts of it are hidden **behind** the east panel because of this behavior so we have to close the east panel on load of the page (only on  initialization of session scoped bean).

initClosed="true" to me means that when initially visiting the page the panel is closed and if I log out and log back in it should count as a new initial visit.

If this is not possible, it is possible to somehow add this kind of behavior?

**Comment by melloware** [comment]
So as the component stands right now with client state saving = true you are letting your user decide once the page first loads how the panels are laid out for them.  I would think this would be the expected behavior for this feature.  If I told FaceBook i wanted my left panel open and when I came back to the site tomorrow it was closed again i would be annoyed I had to reopen it every time i came back to the site.  So you have a few choices...

1. Don't use client state saving if you want the users to have the original state every time they visit your site.  By disabling this it will respect your initClosed="true" every time.

2. Just override the initClosed yourself with client side JS setting the East panel to closed on page load. Something like...

```javascript
            $( document ).ready(function() {
               PF('layoutWidget').close('east');
            });
```

**Comment by Kameecoding** [comment]
Well I want the client state saving due to the sizes of the panels (because that's usually client side specific, because you rarely change monitors, so If you have set up your layout it should stay the same) but I don't want to close the east panel every time the page loads, just a consistent look when the page is opened.

So based on what you are saying our options are:

- Implement our own version of client side saving, using our own custom cookies
- Or do it as we do now which is to call client side code on initialization of backing bean.

**Comment by melloware** [comment]
I would say Option 1 or if you discover something clever in the code feel free to submit a PR to make this component better.  I use it right now heavily but have never used the client state saving myself.  But if you come up with an improvement definitely submit it and I will review!
