### ISSUE TITLE
Calculator showcase - alert pop up on page load

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#565]
https://www.primefaces.org/showcase-ext/sections/calculator/basicUsage.jsf

![image](https://user-images.githubusercontent.com/10467831/39448677-46738c5c-4c8b-11e8-9276-80ffb776a22a.png)

**Comment by melloware** [comment]
I think this might be related to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

The calculator does this:
```javascript
if (this.target.is(':input')) {
      input = this.target;
} else {
      input = $(':not(:submit):not(:button):input:visible:enabled:first', this.target);
 }
```

And the jquery ":not(:submit):not(:button):input:visible:enabled:first" is returning nothing because it thinks the input is not visible.  So this all goes back to the layout being a deferred widget and the change for PF 6.2 not to wrap widgets in "function ({});" blocks.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/e28850af5aeb1f2151a88e324eb78b9dec9f9d78

**Comment by jxmai** [comment]
Thanks ! I re-tested and it should work well. But as far as the deferred widget goes, is there a specific timeline that this got broken ? 

> That Layout has been Deferred since PFE 3.0 and it looks like the PF version of Layout is also a DeferredWidget. I will let you know what I find out.

**Comment by melloware** [comment]
It broke with 6.2 and the way scripts don't get wrapped document.ready anymore but thanks for testing this fix!
