### ISSUE TITLE
Sheet: readonly attribute for sheet 

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#582]
There's an attribute "readonly" for sheetcolumn, but it is also possible to render the whole sheet readonly (by giving the underlying handsontable the readOnly: true option.

**Comment by melloware** [comment]
OK added new "readOnly" attribute to the entire sheet.   Also I realized I had the taglib documentation for extender and the new StyleClass attributes under SheetColumn instead of Sheet so I fixed that as well.

Fixed with this commit:  https://github.com/primefaces-extensions/core/commit/8ccdd9c6c5a551fe3e9ac65f034eec7cc765cda8

**Comment by fheldt** [comment]
Works like a charm 👍

Thanks a lot!
