### ISSUE TITLE
Sheet : No visible property on sheetcolumn

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#596]
Version 6.2.7
There no visible property on the sheetcolumn.
So, how is it possible to get a colmun with data on the DOM but not visible and not use by the user intract sheet ?

**Comment by melloware** [comment]
Added a new property on sheetColumn so you can do "visible=false".  I found a clever trick on stack overflow that I can set with width to 0.1 pixels so it is not visible to the human eye but all of the data is still in the DOM!

Fixed with commit: https://github.com/primefaces-extensions/core/commit/ea20db4611c5866618ed2161392ce281ff388143
