### ISSUE TITLE
CKEditor: enable (by default?) browser spellcheck

### ISSUE THREAD

**Issue by aureliaalessio** [primefaces-extensions/primefaces-extensions.github.com#763]
Regarding [https://stackoverflow.com/questions/60597507/how-to-enable-browser-spellcheck-in-peckeditor](https://stackoverflow.com/questions/60597507/how-to-enable-browser-spellcheck-in-peckeditor) I am submitting this feature suggestion. Currently enabling browser spellcheck of the text entered into the editor is disabled and can be enabled only via custom config. 

You might enable the browser spellcheck by default to `true` (which, I believe, is preferred - user can easily and anytime turn this on or off in the browser settings + browser spellcheck usually supports many languages), or eventually an attribute could be added - its value would express if browser spellcheck of the text in the editor is enabled or disabled.

Thank you.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/6f8642416c5ea86b3d6ed751fd0306323005a4f2

New attribute on the CKEditor for disableNativeSpellChecker and I made it "true" by default which matches CKEditor but you can set `disableNativeSpellChecker="false"` on the pe:ckeditor now.

**Comment by melloware** [comment]
8.0.1 is now in Maven Central
